### ISSUE TITLE
[Question] How to open encrypted SQLite database file in DB Browser?

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#17]
I set DB encryption key as 
`DB.encryptionKey = e92450f203bc86d3`
I want to open .sqlite file in «DB Browser for SQLite»
I use [this algorithm ](https://github.com/GetBreeze/breeze-db/blob/master/src/breezedb/BreezeDbInstance.as#L600-L639) to convert the key.
This function returns "e92450f203bc86d3" string
I pass 0xe92460f203bc76d3 to «DB Browser for SQLite» and the password is incorrect.

**Comment by marpies** [comment]
The encryption `String` you are using is converted into `ByteArray` (because that's required by AIR), so that's why the exact `String` token doesn't work in 3rd party programs. You may want to debug the algorithm used by BreezeDb and see the exact bytes that are used in the final `ByteArray`, but I'm not really sure how to input that into DB Browser (maybe a sequence of integers?).

You may have to avoid using encryption when running development builds on your machine and only encrypt the database for production builds.

**Comment by subdan** [comment]
Ok. Thanks.
