### ISSUE TITLE
I want to know how to setup ORM Relationship.

### ISSUE THREAD

**Issue by theashywolf** [GetBreeze/breeze-db#4]
First of all, thank you for the good code. I'm cheering for you. and sorry about my poor english.

I have question. I want to be able to import other models that had relationship to the inside of implemented BreezeModel file. How shall I do it?

```
public function get parent():ParentModel {
	return ParentModel.query().find(
		this.foreignKey,
		function(err:Error, p:ParentModel):ParentModel {
			return p;
		}
	);
}
```

I tried this one, and of course not wok. can I excuse you?

**Comment by marpies** [comment]
@theashywolf 
Thanks for the kind words, we're happy you find the project useful.

Your example doesn't work because the `find` method executes asynchronously and the model you're looking for (`ParentModel`) isn't immediately available, thus cannot be returned when you call `get parent():ParentModel`.

You could change it to something like this:

```as3
public function getParent(callback:Function):void {
	ParentModel.query().find(
		this.foreignKey,
		function(err:Error, p:ParentModel):void {
			callback(p); // Trigger the callback with the found model (can be null)
		}
	);
}

...

model.getParent(parentLoaded);

private function parentLoaded(p:ParentModel):void {
    // Use the model
}
```

All BreezeDb queries are asynchronous so you have to write your code accordingly. Does that help with your question?

**Comment by theashywolf** [comment]
Thank you for your quick response, and it was very helpful.
I can sleep comfortably today.
