### ISSUE TITLE
Unable to open encrypted DB file

### ISSUE THREAD

**Issue by subdan** [GetBreeze/breeze-db#7]
I want to encrypt DB. I set an encryption key before calling setup:
DB.encryptionKey = "apple";
DB.setup(function (error:Error):void

When I try to open my DB file in «DB Browser for SQLite» my encryption key doesn't work.

![screenshot_2](https://user-images.githubusercontent.com/410293/41958492-844ab42e-79ea-11e8-99ce-cdc28cef5aed.png)
![screenshot_1](https://user-images.githubusercontent.com/410293/41958494-8468331e-79ea-11e8-9750-b28a1fb70f02.png)

**Comment by marpies** [comment]
SQLite in AIR requires the encryption key to be a `ByteArray` that contains exactly 16 bytes. The `ByteArray` is generated from the value you provide [using this algorithm](https://github.com/GetBreeze/breeze-db/blob/master/src/breezedb/BreezeDbInstance.as#L600-L639), therefore you can't use the original value to decrypt the database in other programs. You could try extracting the exact `ByteArray` bytes and try using that, but I can't say whether it will work because it's not clear how exactly AIR encrypts the file.

**Comment by subdan** [comment]
Ok, Got it. Thanks.
